FROM docker.io/library/python:3.11.3

COPY requirements.txt /tmp/requirements.txt

RUN sed -i 's/==/>=/g' /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt

RUN rm /tmp/requirements.txt
