FROM docker.io/library/python:slim-bullseye

COPY requirements.txt /tmp/requirements.txt

RUN sed -i 's/==/>=/g' /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt --upgrade

RUN rm /tmp/requirements.txt
