# Use your custom Python 3.11 environment as the base image
FROM localhost/python-evn-3-11:latest

RUN mkdir /opt/vscode-server/

COPY extensions /opt/vscode-server/

WORKDIR /opt/vscode-server/

CMD [ "/bin/bash", "-c", "/opt/vscode-server/extensions.sh" ]
