# Use your custom Python 3.11 environment as the base image
FROM localhost/python-evn-3-11

RUN mkdir /opt/vscode-server/

COPY extensions /opt/vscode-server/

WORKDIR /opt/vscode-server/

RUN chmod +x ./download-vs-code-server.sh

RUN ./download-vs-code-server.sh

