# Use your custom Python 3.11 environment as the base image
FROM docker.io/library/python:latest
RUN pip install mkdocs

RUN pip install mkdocs-material
RUN apt update
RUN apt install nginx -y

COPY ./base_nginx_conf /etc/nginx/nginx.conf

RUN ln -s -f /dev/stdout /var/log/nginx/access.log
RUN ln -s -f /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]